Removing the pidfiles is probably a good idea

diff --git a/watchman b/watchman
--- a/watchman
+++ b/watchman
@@ -249,6 +249,14 @@ watchman.stop() {
 					return 23
 				}
 			}
+
+			for i in "${service_pidfile}" "${service_pidfile_int}"; do
+				[[ -e "$i" ]] && {
+					rm "$i" || {
+						watchman.err "Failed to remove pidfile: $i"
+					}
+				}
+			done
 		;;
 	esac
 }
