merge

diff --git a/watchman b/watchman
--- a/watchman
+++ b/watchman
@@ -19,14 +19,19 @@
 # IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 # OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+# Config
+
+
+
 # Functions
 
 watchman.usage() {
 	echo "Usage: watchman [flags] <service> <action>"
 	echo "Flags:"
 	echo "	-u, --user		Force user mode"
-	echo "	-s, --system		Force system mode"
+	echo "	-s, --system	Force system mode"
 	echo "	-h, --help		Show this message"
+	echo "	-v, --verbose	Verbose output"
 }
 
 watchman.getopt() {
@@ -59,13 +64,14 @@ watchman.args() {
 			-u|--user) flag_user='1';;
 			-s|--system) unset flag_user;;
 			-h|--help) watchman.usage; exit 0;;
+			-v|--verbose) flag_verbose='1';;
 
 			-t|--test) watchman.msg "(debug) test='$2'"; shift;;
 
 			-*)
 				watchman.err "Invalid key: $1"
 				watchman.usage
-				exit 1
+				return 1
 			;;
 
 			*) args+=( "$1" );;
@@ -76,38 +82,56 @@ watchman.args() {
 
 watchman.msg() { echo "[watchman] $1"; }
 watchman.err() { watchman.msg "(error) $1"; }
-
-watchman.die() { exit "$1"; }
-watchman.cleanup() { true; } # Placeholder
+watchman.debug() {
+	[[ "$flag_verbose" ]] && {
+		watchman.msg "{v} $1"
+	}
+}
 
 watchman.init() {
+	[[ "$UID" == '0' ]] || { flag_user='1'; }
+	watchman.args "$@" || { return 3; }
+
+	[[ "$flag_user" ]] && {
+		cfg_dir="${cfg_dir_user:-$HOME/.watchman}"
+		cfg_tmpdir="${cfg_tmpdir_user:-/tmp/$USER/watchman}"
+	} || {
+		cfg_dir="${cfg_dir_system:-/etc/watchman}"
+		cfg_tmpdir="${cfg_tmpdir_system:-/run/watchman}"
+	}
+
+	cfg_rundir="$cfg_tmpdir/run"
+	cfg_logdir="$cfg_tmpdir/log"
+	cfg_initdir="$cfg_dir/init.d"
+
+	cfg_init_dirs+=( "$cfg_dir" "$cfg_tmpdir" "$cfg_rundir" "$cfg_initdir" "$cfg_logdir" )
+
 	for i in "${cfg_init_dirs[@]}"; do
-		[[ -d "$i" ]] || {
-			watchman.msg "$i does not exist, attempting to create..."
-			mkdir -p "$i" && {
-				watchman.msg "Success!"
-			} || {
+		[[ -e "$i" ]] || {
+			watchman.debug "$i does not exist, creating..."
+			mkdir -p "$i" || {
 				watchman.err "Can't create $i, exiting"
-				watchman.die 9
+				return 5
 			}
 		}
 	done
 
-	[[ -e "$cfg_cfgdir/config.sh" ]] && { source "$cfg_cfgdir/config.sh" || return 1; }
-	[[ -e "$cfg_cfgdir/config.d" ]] && {
-		for i in `ls $cfg_cfgdir/config.d`; do
-			source "$cfg_cfgdir/config.d/$i"
+	[[ -e "$cfg_cfgdir/conf.d" ]] && {
+		for i in `ls cfg_cfgdir/config.d`; do
+			source "$cfg_cfgdir/conf.d/$i"
 		done
 	}
+
+	return 0
 }
 
 watchman.start() {
 	watchman.status && {
-		watchman.err "$sname is already running"
-		return 1
+		watchman.err "$service_name is already running"
+		return 7
 	}
 
-	[[ "$service_command" ]] || { service_command=`which "$sname"`; }
+	[[ "$service_command" ]] || { service_command=`which "$service_name"`; }
 	[[ "$service_command" ]] || {
 		watchman.err "Please specify what to run with \$service_command"
 	}
@@ -117,94 +141,60 @@ watchman.start() {
 	[[ "$service_username" ]] && {
 		[[ "$UID" == '0' ]] || {
 			watchman.err "You can't use \$service_username if you are not root!"
-			return 1
+			return 19
 		}
-
 		su -s "$BASH" "$service_username" -c "$service_command $service_args" &>"$service_logfile" &
 	} || {
 		"$service_command" $service_args &>"$service_logfile" &
 	}
 
-	[[ "$service_pidfile" ]] && {
-		[[ -f "$service_pidfile" ]] && { service_pid=`cat "$service_pidfile"`; }
-	} || {
-		service_pid="$!"
-	}
-	
-	echo "$service_pid" > "$service_tech_pidfile"
+	case "$service_type" in
+		oneshot)
+			touch "$cfg_rundir/${service_name}.done"
+			watchman.msg "$service_name enabled"
+		;;
 
-	watchman.msg "$sname started ($service_pid)"
-
-	return 0
+		*)
+			[[ "$service_pidfile" ]] && {
+				[[ -f "$service_pidfile" ]] && { service_pid=`cat "$service_pidfile"`; }
+			} || {
+				service_pid="$!"
+			}
+			
+			echo "$service_pid" > "$service_pidfile_int"
+			watchman.msg "$service_name started ($service_pid)"
+		;;
+	esac
 }
 
-watchman.stop() {
-	local timeout
-
-	watchman.status || {
-		watchman.err "$sname doesn't seem to be running"
-		return 1
-	}
-
-	[[ -f "$cfg_rundir/${sname}.done" ]] && {
-		watchman.undone
-		watchman.err "$sname is a oneshot service, but it doesn't have a custom stop function! Removed $cfg_rundir/${sname}.done."
-		return 1
-	}
-
-	timeout='30'
-
-	kill "$service_pid"
-
-	ps -p "$service_pid" &>/dev/null && {
-		watchman.pid_wait || {
-			watchman.err "Failed to stop $sname"
-			return 1
-		}
-	}
-
-	watchman.msg "$sname stopped"
-	return 0
-}
-
-watchman.status() {
-	[[ -f "$cfg_rundir/${sname}.done" ]] && { return 0; }
-
-	[[ "$service_pid" ]] && {
-		ps -p "$service_pid" &>/dev/null && { return 0; }
-	}
-
-	return 1
-}
-
-watchman.reload() {
-	watchman.status || {
-		watchman.err "$sname doesn't seem to be running"
-		return 1
-	}
-
-	kill -HUP ${service_pid} && {
-		watchman.msg "Reloading ${sname}..."
-	} || {
-		watchman.err "Failed to reload $sname"
-		return 1
-	}
-
-	return 0
-}
-
-watchman.watch() {
+watchman.respawn() {
 	while true; do
 		wait "$service_pid"
-		watchman.start
+		start
 	done
+}
+
+watchman.depends() {
+	[[ "$action" == 'start' ]] || { return 0; }
+
+	for s in "$@"; do
+		watchman "$s" status >/dev/null || {
+			watchman.msg "$sname depends on $s, so starting ${s}..."
+			"$0" "$s" start || {
+				watchman.err "Starting $s failed, aborting."
+				return 31
+			}
+		}
+	done
+
+	return 0
 }
 
 watchman.pid_wait() {
 	local rc='0'
-	echo -n "[watchman] Waiting for PID to exit: $service_pid..."
+	echo -n "[watchman] Waiting for PID to exit: ${1}..."
 
-	while [[ "$counter" -lt "$timeout" ]] && { ps -p "$service_pid" &>/dev/null; }; do
+	while [[ "$counter" -lt "$timeout" ]] && { ps -p "$1" &>/dev/null; }; do
 		echo -n '.'
 		sleep 1
 		local counter=$[counter+1]
@@ -216,163 +206,147 @@ watchman.pid_wait() {
 	return "$rc"
 }
 
-watchman.depends() {
-	[[ "$action" == 'start' ]] || { return 0; }
+watchman.stop() {
+	service_stop_timeout="${service_stop_timeout:-30}"
 
-	for s in "$@"; do
-		watchman "$s" status >/dev/null || {
-			watchman.msg "$sname depends on $s, so starting ${s}..."
-			"$0" "$s" start || {
-				watchman.err "Starting $s failed, aborting."
-				return 1
+	watchman.status || {
+		watchman.err "$service_name doesn't seem to be running"
+		return 21
+	}
+
+	case "$service_type" in
+		oneshot)
+			watchman.msg "Removing $cfg_rundir/${service_name}.done file..."
+			rm "$cfg_rundir/${service_name}.done"
+		;;
+
+		*)
+			kill "$service_pid"
+
+			kill -0 "$service_pid" &>/dev/null && {
+				watchman.pid_wait "$service_pid" || {
+					watchman.err "Failed to stop $service_name"
+					return 23
+				}
 			}
-		}
-	done
+		;;
+	esac
+}
 
-	return 0
+watchman.status() {
+	case "$service_type" in
+		oneshot)
+			[[ -e "$cfg_rundir/${service_name}.done" ]] && { return 0; }
+		;;
+
+		*)
+			[[ "$service_pid" ]] && {
+				ps -p "$service_pid" &>/dev/null && { return 0; }
+			}
+		;;
+	esac
+
+	return 25
 }
 
 watchman.service_usage() {
+	local valid_actions
+
 	for i in ${service_actions[@]}; do
-		type -t "$i" &>/dev/null && { _actions+="$i|"; }
+		type -t "$i" &>/dev/null && { valid_actions+="$i|"; }
 	done
-	watchman.msg "Usage: $sname <${_actions%|*}>"
-	watchman.die 11
+
+	watchman.msg "Usage: $service_name <${valid_actions%|*}>"
 }
 
-watchman.done() { touch "$cfg_rundir/${sname}.done"; }
-watchman.undone() { rm "$cfg_rundir/${sname}.done"; }
+start() { watchman.start; return "$?"; }
+stop() { watchman.stop; return "$?"; }
+restart() { stop; start; return "$?"; }
+status() {
+	local service_status
 
-# Default functions
+	watchman.status && {
+		service_status='running'
+	}
 
-start() { watchman.start; }
-stop() { watchman.stop; }
-restart() { stop; start; }
-reload() { watchman.reload; }
+	[[ "$service_status" ]] && {
+		[[ "$service_type" == 'oneshot' ]] && {
+			watchman.msg "$service_name is enabled"
+		} || {
+			watchman.msg "$service_name is running ($service_pid)"
+		}
+
+		return 0
+	} || {
+		watchman.msg "$service_name is down"
+	}
+
+	return 33
+}
 
 watch() {
 	watchman.status && {
-		watchman.err "$sname is already running ($service_pid)"
-		return 1
+		watchman.err "$service_name is already running"
+		return 29
 	}
 
 	start
-	watchman.watch
+	watchman.respawn
 }
 
-status() {
-	watchman.status && {
-		[[ "$service_pid" ]] && {
-			watchman.msg "$sname is running ($service_pid)"
-		} || {
-			watchman.msg "$sname is enabled"
-		}
-	} || {
-		watchman.msg "$sname is down"
-		return 1
+watchman.main() {
+	watchman.init "$@" || { return "$?"; }
+
+	[[ "${args[0]}" ]] || {
+		watchman.usage
+		return 9
 	}
-}
 
-trap watchman.cleanup EXIT
+	service_name="${args[0]##*/}"
+	service_logfile="$cfg_logdir/${service_name}.log"
+	service_pidfile_int="$cfg_rundir/${service_name}.pid"
 
-# Arguments and options:
+	action="${args[1]}"
 
-[[ "$UID" == '0' ]] || { flag_user='1'; }
+	[[ -f "$service_pidfile_int" ]] && { service_pid=`cat "$service_pidfile_int"`; }
+	[[ "$service_actions" ]] || { service_actions=( 'start' 'stop' 'restart' 'reload' 'status' ); }
+	[[ -d "$cfg_cfgdir/groups/$service_name" ]] && { service_type='group'; }
+	
+	service_type=${service_type:-single}
 
-watchman.args `watchman.getopt "$@"` || exit 13
-
-[[ "$flag_user" ]] && {
-	cfg_cfgdir="$HOME/.watchman"
-	cfg_tmpdir="/tmp/$USER/watchman"
-} || {
-	cfg_cfgdir='/etc/watchman'
-	cfg_tmpdir='/run/watchman'
-}
-
-cfg_rundir="$cfg_tmpdir/run"
-cfg_initdir="$cfg_cfgdir/init.d"
-cfg_logdir="$cfg_tmpdir/log"
-
-cfg_init_dirs+=( "$cfg_cfgdir" )
-cfg_init_dirs+=( "$cfg_tmpdir" )
-cfg_init_dirs+=( "$cfg_rundir" )
-cfg_init_dirs+=( "$cfg_initdir" )
-cfg_init_dirs+=( "$cfg_logdir" )
-cfg_init_dirs+=( "$cfg_cfgdir/groups/all" )
-
-# Main:
-
-watchman.init
-
-[[ "${args[0]}" ]] || {
-	watchman.usage
-    watchman.die 9
-}
-
-sname=`basename ${args[0]}`
-
-action="${args[1]}"
-
-service_logfile="$cfg_logdir/$sname.log"
-service_fifo="$cfg_rundir/$sname.fifo"
-service_tech_pidfile="$cfg_rundir/$sname.pid"
-
-[[ -f "$service_tech_pidfile" ]] && { service_pid=`cat "$service_tech_pidfile"`; }
-
-[[ "$service_actions" ]] || { service_actions=( 'start' 'stop' 'restart' 'reload' 'status' ); }
-
-[[ -d "$cfg_cfgdir/groups/$sname" ]] && { service_type='group'; }
-
-[[ "$service_type" ]] || { service_type='service'; }
-
-case "$service_type" in
-	group)
-		group_services=( `ls "$cfg_cfgdir/groups/$sname"` )
-
-		[[ "$group_services" ]] || {
-			[[ "$sname" == 'all' ]] && { group_services=( `ls "$cfg_initdir"` ); }
-		}
-
-		[[ "$group_services" ]] || {
-			watchman.err "No services in group $sname"
-			watchman.die 15
-		}
-
-		for i in "${group_services[@]}"; do
-			[[ -h "$cfg_cfgdir/groups/$sname/$i" ]] && {
-				service_script=`realpath "$cfg_cfgdir/groups/$sname/$i"`
-				"$service_script" "$action" || { exitcode='1'; }
+	case "$service_type" in
+		single)
+			[[ -e "${args[0]}" ]] && {
+				service_script="${args[0]}"
 			} || {
-				"$0" "$i" "$action" || { exitcode='1'; }
+				[[ -e "$cfg_initdir/$service_name" ]] && {
+					service_script="$cfg_initdir/${args[0]}"
+				}
 			}
-		done
-	;;
 
-	service)
-		[[ -f "$cfg_initdir/$sname" ]] && {
-			source "$cfg_initdir/$sname" || {
-				watchman.err "Service script exited abnormally"
-				watchman.die 13
+			[[ "$service_script" ]] || {
+				watchman.err "$service_name doesn't exist in $cfg_initdir"
+				return 11
 			}
-		} || {
-			watchman.err "$sname doesn't exist in $cfg_initdir"
-			watchman.die 3
-		}
 
+			source "$service_script" || { return 13; }
 
-		[[ "$action" ]] || { watchman.service_usage; }
+			[[ "$action" ]] || { watchman.service_usage; return 27; }
 
-		[[ "$service_pidfile" ]] && {
-			[[ -f "$service_pidfile" ]] && { service_pid=`cat "$service_pidfile"`; }
-		}
+			[[ "$service_pidfile" ]] && {
+				[[ -f "$service_pidfile" ]] && { service_pid=`cat "$service_pidfile"`; }
+			}
 
-		type -t "$action" &>/dev/null && {
-			"$action" || { exitcode='1'; }
-		} || {
-			watchman.err "Function $action is not defined for $sname"
-			watchman.die 11
-		}
-	;;
-esac
+			type -t "$action" &>/dev/null && {
+				"$action" || { return "$?"; }
+			} || {
+				watchman.err "Function $action is not defined for $service_name"
+				return 17
+			}
+		;;
+	esac
+}
 
-[[ "$exitcode" ]] && { exit "$exitcode"; } || { exit 0; }
+# Main
+watchman.main "$@"
+exit "$?"
